clean up style

diff --git a/someonewhocares b/someonewhocares
--- a/someonewhocares
+++ b/someonewhocares
@@ -31,20 +31,18 @@ uninstall() {
 	fe80::1%lo0	localhost
 	EOF)
 	echo '> replacing host file'
-	if ! _install <<< "$default"; then
-		echo '> failed!' >&2
-		return 1
-	fi
+	_install <<< "$default" || return 1
 	echo '> done'
 }
 
 # install a host file into place taken over stdin
 _install() {
 	local hosts=$(cat)
-	if ! tee /etc/hosts <<< "$hosts" > /dev/null; then
-		echo '> failed - retrying with sudo' >&2
-		sudo tee /etc/hosts <<< "$hosts" > /dev/null
-	fi
+	tee /etc/hosts <<< "$hosts" > /dev/null && return
+	echo '> failed - retrying with sudo' >&2
+	sudo tee /etc/hosts <<< "$hosts" > /dev/null && return
+	echo '> failed with sudo - giving up' >&2
+	return 1
 }
 
 _type=
@@ -79,9 +77,6 @@ echo 'passed'
 
 # install host file
 echo '> installing new host file'
-if ! _install <<< "$hosts"; then
-	echo '> failed!' >&2
-	exit 3
-fi
+_install <<< "$hosts" || exit $?
 
 echo "> finished! $(grep 'Last updated: ' <<< "$hosts")"
